name: 'Test Repo CI/CD'
on:
  pull_request:
    branches:
      - 'main'
jobs:
  algosec-iac-connectivity-risk-analysis:
    name: 'Algosec IAC Connectivity Risk Analysis'
    runs-on: ubuntu-latest
    steps:
      - name: TEST ALON
        uses: actions/checkout@v3

         
