name: 'Your Repo CI/CD Yaml Workflow'
on:
  pull_request:
    branches:
      - 'master'
      - 'main'
jobs:
  algosec-iac-connectivity-risk-analysis:
    name: 'Algosec IAC Connectivity Risk Analysis'
    runs-on: ubuntu-latest
    steps:
      # Read how to create GCP_CREDENTIALS key from GCP Json file:
      # https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/provider_reference
      # Auth Gcp Action https://github.com/google-github-actions/auth
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.7.3
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Connectivity Risk Analysis
        uses: algosec/connectivity-risk-analysis-action@v0.0.41
        env:
          # By default our action doesn't require actions/checkout, using GCP Auth action requires us to specify its usage
          USE_CHECKOUT: true
          ######
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CF_TENANT_ID: ${{ secrets.CF_TENANT_ID }}
          CF_CLIENT_ID: ${{ secrets.CF_CLIENT_ID }}
          CF_CLIENT_SECRET: ${{ secrets.CF_CLIENT_SECRET }}